### ISSUE TITLE
大佬，怎么用了一天，第二天打不开了？

### ISSUE THREAD

**Issue by qq5931462** [xbb2yy/scan#2]
第一天好着呢，然后第二天打开软件收到“Error invoking method”然后“Failed to launch JVM”的错误消息

**Comment by xbb2yy** [comment]
我加你，帮你看下

**Comment by xbb2yy** [comment]
你会Java不，你可以直接把项目clone下来，导入到自己的ide里看看运行报不报错

**Comment by qq5931462** [comment]
不会，我是在吾爱看到的，只能在这里求助，吾爱那个帖子已经关了，回复不了了。大佬，能帮忙弄一下吗？

**Comment by qq5931462** [comment]
> 你会java不，你可以直接把项目克隆下来，导入到自己的ide里看看运行报不报错

不会，我是在吾爱看到的，只能在这里求助，吾爱那个帖子已经关了，回复不了了。大佬，能帮忙弄一下吗？

**Comment by xbb2yy** [comment]
你加我qq2008699，你的q我加不了，要回答问题，这个项目我两个月没看了，我尽量帮你看看
